name: Upload Windows MSI to Dolt Release

on:
  repository_dispatch:
    types: [ upload-msi ]
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format dolt release tag, i.e. 0.24.5'
        required: true
      go_version:
        description: 'go version to build binaries at'
        required: false
        default: "1.15.11"

jobs:
  build-release-binaries:
    name: Build Release Binaries
    runs-on: ubuntu-18.04
    outputs:
      release_id: ${{ steps.get_release.outputs.release_id }}
    steps:
      - name: Checkout code
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2
        with:
          repository: dolthub/dolt
          ref: v${{ github.event.inputs.version }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Checkout code
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: actions/checkout@v2
        with:
          repository: dolthub/dolt
          ref: ${{ github.event.client_payload.tag }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Get Release
        id: get_release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          release_id=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/dolthub/dolt/releases/tags/v${{ github.event.inputs.version }} | jq '.id')
          echo "::set-output name=release_id::$release_id"
      - name: Get Release
        id: get_release
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "::set-output name=release_id::$RELEASE_ID"
        env:
          RELEASE_ID: ${{ github.event.client_payload.release_id }}
      - name: Build Binaries
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          GO_BUILD_VERSION=${{ github.event.client_payload.go_version }} go/utils/publishrelease/buildbinaries.sh
      - name: Build Binaries
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          GO_BUILD_VERSION=${{ github.event.inputs.go_version }} go/utils/publishrelease/buildbinaries.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dolt-windows-amd64-latest
          path: go/out/dolt-windows-amd64.zip

  upload-windows-msi:
    needs: build-release-binaries
    name: Upload Windows MSI to Dolt Release
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows MSI
        run: |
          mkdir archives
          mkdir output
      - uses: actions/download-artifact@v2
        with:
          name: dolt-windows-amd64-latest
          path: archives/dolt-windows-amd64.zip
      - name: Run Process.bat
        run: |
          ./process.bat
      - name: Upload MSI to Dolt Release
        uses: actions/github-script@v4
        with:
         debug: true
         github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
         script: |
           const fs = require('fs');
           const path = require('path')

           try {
             const data = fs.readFileSync(path.join(process.env.WORKSPACE, "output", "dolt-windows-amd64.msi"))
             const res = await github.repos.uploadReleaseAsset({
               owner: "dolthub",
               repo: "dolt",
               name: "dolt-windows-amd64.msi",
               release_id: parseInt(process.env.RELEASE_ID, 10),
               data,
             });
             console.log("Successfully uploaded windows msi", res)
           } catch (err) {
             console.log("Error", err);
             process.exit(1);
           }

        env:
         WORKSPACE: ${{ github.workspace }}
         RELEASE_ID: ${{ needs.build-release-binaries.outputs.release_id }}
